<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ZJS2310.Core\ZJS2310.Core.csproj" />
    <ProjectReference Include="..\..\src\ZJS2310.App\ZJS2310.App.csproj" />
  </ItemGroup>
</Project>
